'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
function atomic(file,value){const tmp=`${file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(value),{encoding:'utf8',mode:0o600});fs.renameSync(tmp,file);}
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
class InternalBridge{
 constructor({dataDir,fetchImpl=globalThis.fetch}){this.fetch=fetchImpl;this.configFile=path.join(dataDir,'bridge-config.json');this.queueFile=path.join(dataDir,'internal-queue.json');this.conflictsFile=path.join(dataDir,'internal-conflicts.json');this.stateFile=path.join(dataDir,'internal-state.json');}
 config(){return read(this.configFile,{url:'',apiKey:''});} queue(){return read(this.queueFile,[]);} conflicts(){return read(this.conflictsFile,[]);} state(){return read(this.stateFile,{version:0,lastSyncAt:null});}
 setConfig(input){let url=String(input.url||'').trim().replace(/\/+$/,'');if(url){const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw Error('invalid_internal_url');}const previous=this.config(),config={url,apiKey:Object.prototype.hasOwnProperty.call(input,'apiKey')?String(input.apiKey||''):previous.apiKey};atomic(this.configFile,config);return{url,configured:!!url};}
 headers(){const h={'content-type':'application/json'};if(this.config().apiKey)h['x-api-key']=this.config().apiKey;return h;}
 async request(endpoint,options={}){const {url}=this.config();if(!url)throw Error('internal_not_configured');const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{return await this.fetch(`${url}/${endpoint}`,{...options,headers:{...this.headers(),...(options.headers||{})},signal:c.signal});}finally{clearTimeout(timer);}}
 async ping(){const r=await this.request('ping');if(!r.ok)throw Error(`internal_ping_${r.status}`);return r.json();}
 async heartbeat(value){const r=await this.request('heartbeat',{method:'POST',body:JSON.stringify(value)});if(!r.ok)throw Error(`internal_heartbeat_${r.status}`);return r.json();}
 enqueue(item){const q=this.queue().filter(x=>!(['store','website'].includes(item.type)&&x.type===item.type)&&!(item.type==='attachment'&&x.type==='attachment'&&x.key===item.key));q.push({...item,operation_id:item.operation_id||crypto.randomUUID(),createdAt:new Date().toISOString()});atomic(this.queueFile,q);return q.at(-1);}
 async mirrorWebsite(store){const item=this.enqueue({type:'website',operation_id:`website-${store.version}-${crypto.createHash('sha1').update(JSON.stringify(store.db)).digest('hex').slice(0,12)}`,source_version:store.version,updated_at:store.updatedAt,db:store.db});return this.flush();}
 enqueueStore(db,actor){return this.enqueue({type:'store',base_version:this.state().version,db,actor});}
 enqueueAttachment(key,value,method='PUT',actor,source='Windows EXE'){return this.enqueue({type:'attachment',key,value,method,actor,source});}
 recordConflict(item,remote){const c=this.conflicts();if(c.some(conflict=>conflict.id===item.operation_id&&conflict.remote?.version===remote?.version))return;c.push({id:item.operation_id,detectedAt:new Date().toISOString(),local:item,remote});atomic(this.conflictsFile,c.slice(-500));}
 async flush(){const q=this.queue();if(!q.length)return{synced:0,pending:0,conflicts:0};let synced=0,conflicts=0,remaining=[];for(let i=0;i<q.length;i++){const item=q[i];try{let r;if(item.type==='website')r=await this.request('store',{method:'PUT',body:JSON.stringify(item)});else if(item.type==='store')r=await this.request('sync',{method:'POST',body:JSON.stringify({...item,base_version:this.state().version})});else r=await this.request(`attachments?key=${encodeURIComponent(item.key)}`,{method:item.method,body:JSON.stringify(item)});if(r.status===409){this.recordConflict(item,await r.json().catch(()=>({})));conflicts++;continue;}if(!r.ok)throw Error(`internal_write_${r.status}`);const result=await r.json();if(result.version)atomic(this.stateFile,{version:result.version,lastSyncAt:new Date().toISOString()});synced++;}catch{remaining=q.slice(i);break;}}atomic(this.queueFile,remaining);return{synced,pending:remaining.length,conflicts};}
 async status(){let online=false,info=null;try{info=await this.ping();online=true;if(info.version)atomic(this.stateFile,{version:info.version,lastSyncAt:this.state().lastSyncAt});}catch{}return{configured:!!this.config().url,url:this.config().url,online,pending:this.queue().length,conflicts:this.conflicts().length,lastSyncAt:this.state().lastSyncAt,info};}
}
module.exports={InternalBridge};
